# Generated by Django 4.2.6 on 2024-01-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_school_email_school_reenteremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='ReenterEmail',
            field=models.EmailField(max_length=254),
        ),
    ]
